Àlgebra Lineal Numèrica - Óscar Rodríguez

# Pràctica 1: Determinació Orbital

## Objectius:



*   Programar i utilitzar el mètode de factorització $QR$ per resoldre un sistema lineal.

*   Programar i utilitzar la norma 1, euclidea i infinit per seleccionar la solució més adient.



## Introducció:

Considerem un sistema de referència heliocèntric (és a dir, el Sol està situat a l'origen) definit per les coordenades cartesianes $x$, $y$, $z$.
Com a simplificació, assumirem que la Terra és una massa puntual que es mou en el pla $z=0$ en una òrbita circular al voltant del Sol de radi $r_\oplus$.

Les unitats amb les quals treballarem estan normalitzades, és a dir, notant per $G$ la constant gravitatòria de Newton i per $m_\odot$, $m_\oplus$ les masses del Sol i la Terra respectivament, estem triant unitats de longitud, massa i temps assumint que:

$$
r_\oplus= 1, \qquad
m_\odot=1, \qquad
G\left(m_\odot+m_\oplus\right) = 1.
$$

##### Equacions del moviment

Denotarem a més per $\boldsymbol{r}_\odot(t)$, $\boldsymbol{r}_\oplus(t)$, $\boldsymbol{r}_\ominus(t)\in\mathbb{R}^3$
les posicions a temps $t$ del Sol, de la Terra i de l'asteroide. Notem que, com estem en un sistema de referència heliocèntric $\boldsymbol{r}_\odot\equiv\boldsymbol{0}$. Així, suposant que el moviment de l'asteroide només està influït pel Sol, tenim que el moviment de la Terra i l'asteroide es descriuen mitjançant les següents equacions:

$$
    \begin{aligned}
        \ddot{\boldsymbol{r}}_\oplus & = -\frac{G\left(m_\odot+m_\oplus\right)}{||\boldsymbol{r}_\oplus||^3}\boldsymbol{r}_\oplus,\\
        \ddot{\boldsymbol{r}}_\ominus & = -\frac{Gm_\odot}{||\boldsymbol{r}_\ominus||^3} \boldsymbol{r}_\ominus,
    \end{aligned}
$$

on $\dot{}$ denota la derivada respecte al temps $t$ i, en conseqüència, $\ddot{}$ denota la segona derivada respecte $t$.

A més, utilitzant que la Terra descriu una òrbita circular al voltant del Sol, assumint la simplificació de les unitats de longitud, massa i temps, i triant unes condicions inicials adients per $t=0$, tenim que el moviment de la Terra ve descrit per:

$$
    \boldsymbol{r}_\oplus(t) = (\cos t, \sin t, 0),
$$

i, per tant, també tenim que

$$
\boldsymbol{v}_\oplus(t) = \dot{\boldsymbol{r}}_\oplus(t) = (-\sin t, \cos t, 0).
$$

Pel que fa a l'asteroide, utilitzant la simplificació de les unitats, podem reescriure la seva equació de moviment com

$$
  \ddot{\boldsymbol{r}}_\ominus = -\frac{K}{||\boldsymbol{r}_\ominus||^3} \boldsymbol{r}_\ominus,
$$

on $K=\cfrac{332946}{332947}$ (utilitzant que la ràtio entre les masses del Sol i de la Terra és aproximadament $332946$).

##### Com determinem el moviment de l'asteroide?

Per determinar el moviment de l'asteroide, és essencial conèixer la seva posició i velocitat a un instant de temps determinat. Aquestes dades són fonamentals per calcular la seva trajectòria passada o futura, la qual podrem calcular amb l'equació de moviment.

Conèixer (i mesurar) la posició $\boldsymbol{r}_\ominus$ i velocitat $\dot{\boldsymbol{r}}_\ominus$ de l'asteroide a un instant de temps determinat no és una feina trivial, ja que, quan observem un objecte celeste no sabem a priori a quina distància es troba. Vegem-ho en més detall al següent punt.

##### Observacions òptiques d'asteroides

Quan observem un asteroide des de la Terra, utilitzem les seves coordenades celestials per localitzar-lo al cel:

*   L' **ascensió recta** $\alpha$, és l'equivalent celeste a la longitud terrestre, és un angle.

*   La **declinació** $\delta$, és l'equivalent celeste a la latitud terrestre, i d'igual manera, és un angle.

D'aquesta forma, tots els valors $(\alpha,\delta)$ possibles formen el que es coneix com a esfera celeste.

Notem però que per conèixer la posició exacta a un instant de l'objecte necessitem conèixer la distància a la qual es troba de la Terra.



##### El mètode de determinació orbital de Laplace

Considerem un conjunt  de $m\geq 3$ observacions òptiques de l'asteroide $\{(\alpha_i,\delta_i) | i = 1,\ldots,m\}$, on $\alpha_i$, $\delta_i$ són l'ascensió recta i la declinació als temps $t_i$, $i=1,\ldots,m$, les quals considerarem que estan prou pròximes en temps.

A partir d'aquest conjunt d'observacions podem calcular $\alpha(t)$ i $\delta(t)$ amb una aproximació de segon ordre:

$$
\begin{aligned}
        &\alpha(t) \approx \alpha(\bar{t}) + \dot{\alpha}(\bar{t})(t-\bar{t}) + \ddot{\alpha}(\bar{t})\frac{(t-\bar{t})^2}{2},\\
        &\delta(t) \approx \delta(\bar{t}) + \dot{\delta}(\bar{t})(t-\bar{t}) + \ddot{\delta}(\bar{t})\frac{(t-\bar{t})^2}{2},
    \end{aligned}
$$

on $\displaystyle{\bar{t} = \frac{1}{m}\sum_{i=1}^m t_i}$. Podem determinar els coeficients $\alpha(\bar{t})$, $\dot{\alpha}(\bar{t})$, $\ddot{\alpha}(\bar{t})$, $\delta(\bar{t})$, $\dot{\delta}(\bar{t})$, $\ddot{\delta}(\bar{t})$ a partir de les equacions lineals

$$
  \begin{pmatrix}
    1 & t_i-\bar{t} & \cfrac{(t_i-\bar{t})^2}{2}
    \end{pmatrix}
    \begin{pmatrix}
    \alpha(\bar{t}) & \delta(\bar{t}) \\
    \dot{\alpha}(\bar{t}) & \dot{\delta}(\bar{t}) \\
    \ddot{\alpha}(\bar{t}) & \ddot{\delta}(\bar{t})
    \end{pmatrix}
    =
    \begin{pmatrix}
    \alpha_i & \delta_i
    \end{pmatrix},
$$

per $i=1,\ldots,m$.

**Comentari:** Aquest serà el primer punt que haureu de resoldre (teniu més informació posteriorment).

&nbsp;

En aquest punt, ja podem aplicar el mètode de determinació de Laplace, el qual utilitzant la geometria i la dinàmica del problema construeix un polinomi de grau $8$ del qual una de les arrels ens proporciona la solució desitjada. Per fer-ho, també necessitarem calcular la posició i velocitat de la Terra al temps $\bar{t}$.

És important notar que no sempre podem rebutjar les arrels obtingudes del polinomi de grau $8$, i que, per tant, haurem de considerar més d'una solució.

Podeu trobar més informació del mètode al [següent enllaç](http://www.publicacions.ub.es/liberweb/astronomia_esferica/material/version_html/Tomo_2/6_2.htm).

##### Elements orbitals

Els elements orbitals són paràmetres que descriuen l'òrbita d'un cos celeste al voltant d'un altre. Aquests elements són fonamentals per comprendre i predir els moviments dels planetes, satèl·lits i altres objectes en l'espai. En particular, tenim:

* Semieix major ($a$): La meitat de la longitud de l'eix major de l'òrbita el·líptica. Determina la mida de l'òrbita.

* Excentricitat ($e$): Mesura la forma de l'òrbita.

* Inclinació ($i$): L'angle entre el pla de l'òrbita i un pla de referència. Generalment, indica com l'òrbita està inclinada respecte a l'òrbita de la Terra.

* Longitud del node ascendent ($\Omega$): L'angle entre la línia dels nodes (intersecció de l'òrbita amb el pla de referència) i una direcció de referència.


* Argument del periàpside ($\omega$): L'angle que va des del node ascendent fins al periàpside, mesurat en el pla orbital de l'objecte i en el seu sentit de moviment.

* Anomalia Mitjana ($M$): L'angle entre la posició actual de l'objecte i la posició que tindria si l'òrbita fos circular i uniforme.

Podeu trobar més informació al [següent enllaç](https://ca.wikipedia.org/wiki/Elements_orbitals) de la Viquipèdia.

&nbsp;


Per fer-vos una idea més intuïtiva també podeu entrar al [següent enllaç](https://gravitysimulator.org/solar-system/the-solar-system) i al botó add podeu afegir un planeta nan (*Dwarf planet*) i anar variant els seus elements orbitals.

## Part pràctica

### Exercici 1:

Implementa la factorització $QR$ i utilitza-la per determinar els valors dels coeficients $\alpha(\bar{t})$, $\dot{\alpha}(\bar{t})$, $\ddot{\alpha}(\bar{t})$, $\delta(\bar{t})$, $\dot{\delta}(\bar{t})$, $\ddot{\delta}(\bar{t})$.

Per fer-ho hauràs d'utilitzar el fitxer `[número].txt` que conté la informació relativa a diverses observacions. La primera columna conté els valors de l'ascensió recta $\alpha$, la segona els valors de la declinació $\delta$ i la tercera els temps de les observacions. Així, cada fila conté els valors $\alpha_i$, $\delta_i$ i $t_i$ d'una observació òptica.

Podeu llegir aquest fitxer utilitzant la comanda:
```
# Llegim el fitxer numero.txt
observations = np.loadtxt('numero.txt')
```
de `numpy`.


In [6]:
from google.colab import files
uploaded = files.upload() #Leemos los dos ficheros necesarios para la práctica

Saving numbered_asteroids_2024.csv to numbered_asteroids_2024.csv


In [2]:
import numpy as np

def norma_euclidiana(v):
    return np.sqrt(np.sum(v**2))

def factorizacion_QR(A):
    n = len(A[0])
    Q = np.copy(A)  # Inicializamos Q como una copia de A
    R = np.zeros((n, n))

    for i in range(n):
        R[i, i] = norma_euclidiana(Q[:, i])
        Q[:, i] /= R[i, i]  # Normalizamos la columna i de Q

        for j in range(i + 1, n):
            R[i, j] = np.dot(Q[:, i], Q[:, j])
            Q[:, j] -= R[i, j] * Q[:, i]

    return Q, R

def sustitucion_hacia_atras(R, b):
    m, n = b.shape  # Obtener las dimensiones de la matriz b
    x = np.zeros((m, n))  # Inicializar la matriz de soluciones

    for col in range(n):  # Iterar sobre cada columna de b
        for i in range(m - 1, -1, -1):  # Empezar desde la última fila hacia atrás
            x[i, col] = (b[i, col] - np.dot(R[i, i+1:], x[i+1:, col])) / R[i, i]

    return x

observations = np.loadtxt('88.txt')
tiempos = observations[:, 2]

tiempo_medio = np.sum(tiempos) / len(tiempos)

# Construir la matriz A
unos = np.ones_like(tiempos)  # Primera columna de unos
segunda_columna = tiempos - tiempo_medio  # Segunda columna: t_i - tiempo_medio
tercera_columna = ((tiempos - tiempo_medio) ** 2) / 2  # Tercera columna: ((t_i - tiempo_medio) ** 2) / 2

# Combinar las columnas en la matriz A
A = np.column_stack((unos, segunda_columna, tercera_columna))

print("Matriz A:")
print(A)

Q, R = factorizacion_QR(A)
print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)

# Obtener los términos independientes (las dos primeras columnas del archivo)
b = observations[:, :2]

# Resolver el sistema Rx = Q^Tb mediante sustitución hacia atrás
x = sustitucion_hacia_atras(R, np.dot(Q.T, b))

print("Solución del sistema de ecuaciones Rx = (Q^T)b:")
print(x)


Matriz A:
[[ 1.00000e+00 -1.75000e-02  1.53125e-04]
 [ 1.00000e+00 -1.25000e-02  7.81250e-05]
 [ 1.00000e+00 -7.50000e-03  2.81250e-05]
 [ 1.00000e+00 -2.50000e-03  3.12500e-06]
 [ 1.00000e+00  2.50000e-03  3.12500e-06]
 [ 1.00000e+00  7.50000e-03  2.81250e-05]
 [ 1.00000e+00  1.25000e-02  7.81250e-05]
 [ 1.00000e+00  1.75000e-02  1.53125e-04]]
Matriz Q:
[[ 0.35355339 -0.54006172  0.54006172]
 [ 0.35355339 -0.38575837  0.07715167]
 [ 0.35355339 -0.23145502 -0.23145502]
 [ 0.35355339 -0.07715167 -0.38575837]
 [ 0.35355339  0.07715167 -0.38575837]
 [ 0.35355339  0.23145502 -0.23145502]
 [ 0.35355339  0.38575837  0.07715167]
 [ 0.35355339  0.54006172  0.54006172]]
Matriz R:
[[ 2.82842712e+00  6.27969898e-16  1.85615530e-04]
 [ 0.00000000e+00  3.24037035e-02 -1.02999206e-18]
 [ 0.00000000e+00  0.00000000e+00  1.62018517e-04]]
Solución del sistema de ecuaciones Rx = (Q^T)b:
[[ 6.26108147 -0.19989945]
 [-0.22361962  0.03627424]
 [-0.01145714  0.10245714]]


### Exercici 2:

Implementeu les normes vectorials $||\cdot ||_1$, $||\cdot ||_2$ i $||\cdot ||_\infty$.

Un cop implementades, utilitzeu la funció `laplace` definida a continuació per calcular les possibles solucions de l'asteroide. Podeu trobar més informació de la funció mitjançant la comanda `help`. Noteu que haureu de calcular també la posició i la velocitat de la Terra a l'instant $\bar{t}$.

Un cop obtingudes aquestes solucions (en podeu tenir més d'una) calculeu els seus elements orbitals $(a,e,i,\Omega,\omega,M)$ utilitzant la funció `car2kep`.

Un cop calculats, llegiu el fitxer `numbered_asteroids_2024.csv` que conté els elements orbitals dels 2024 primers asteroides numerats i trieu com a solució l'òrbita que més s'assimili a l'òrbita d'un d'aquests asteroides fent ús dels valors $(a,e,i,\Omega,\omega)$, és a dir, calculant la norma de la diferència entre els valors obtinguts i els dels asteroides numerats.

Podeu llegir aquest fitxer mitjançant el codi:



```
# Abans de llegir, hauré de carregar la llibreria pandas amb l'àlies pd
df = pd.read_csv("numbered_asteroids_2024.csv")

# Extraiem la informació relativa a a, e, i, Omega, omega en una matriu
# cada fila conté la informació d'un asteroide:
num_values = df.iloc[:,2:7].to_numpy(dtype = np.float64)
```



Després de fer tot aquest procediment identifiqueu quin és l'asteroide al qual pertanyen les observacions amb les que heu treballat.

## Codi auxiliar

En aquest apartat trobareu codi que us serà d'ajuda per resoldre la pràctica.

#### `Laplace`

In [3]:
import numpy as np

def laplace(rade, r_earth, v_earth, K = 332946./332947.):
  """
  laplace(rade,r_earth,v_earth, K = 332946./332947.) retorna les solucions
      (posició i velocitat) obtingudes amb el mètode de determinació orbital
      de Laplace.

  INPUT:
    - rade: Un array unidimensional que conté els valors:
        alpha, d/dt(alpha), d^2/dt^2(alpha), delta, d/dt(delta), d^2/dt^2(delta)
    - r_earth: Un array que representa la posició de la Terra respecte a un sistema
        de coordenades fix. Suposem que aquest vector és unitari.
    - v_earth: Un array que representa la velocitat de la Terra respecte al mateix
        sistema de coordenades.
    - K: paràmetre opcional que conté el quadrat de la constant de Gauss en les
         unitats adients.
  OUTPUT:
    - solutions: array bidimensional. Cada fila correspon a una solució.
        A cada fila tenim les posicions (x,y,z) i velocitats (v_x,v_y,v_z) de
        la solució.
  """
  # alphas:
  a = rade[0]
  a_t = rade[1]
  a_tt = rade[2]

  # deltas:
  d = rade[3]
  d_t = rade[4]
  d_tt = rade[5]

  # cosa sina, cosd, sind:
  cosa = np.cos(a)
  sina = np.sin(a)
  cosd = np.cos(d)
  sind = np.sin(d)

  # rhohat:
  rhohat = np.array([cosa*cosd,
                     sina*cosd,
                     sind])

  # v:
  v = np.array([-a_t*sina*cosd-d_t*cosa*sind,
                a_t*cosa*cosd-d_t*sina*sind,
                d_t*cosd])

  # eta:
  eta = np.sqrt((a_t*cosd)**2+d_t*d_t)

  # vhat:
  vhat = v/eta

  # nhat:
  nhat = np.cross(rhohat,vhat)

  # eta_t:
  eta_t = (a_tt*a_t*cosd*cosd + d_tt*d_t - a_t*a_t*d_t*cosd*sind)/eta

  # keta2
  keta2 = ((d_tt*a_t - a_tt*d_t)*cosd + a_t*(eta*eta+d_t*d_t)*sind)/eta

  # coseps
  coseps = np.dot(r_earth,rhohat) # suposem r_earth unitari

  # C:
  C = keta2/(K*np.dot(r_earth,nhat))

  # Polinomi:
  p = np.zeros(9)
  p[0] = C*C
  p[2] = -(C*C+2*C*coseps+1)
  p[5] = 2*(C*coseps+1)
  p[8] = -1

  # Arrels del polinomi:
  r = np.roots(p)

  # r real i positiva:
  r_real = r.real[np.abs(r.imag) < 1.e-6] # Com podem tenir error numèric, part imaginària prou petita
  r_real_positive = r_real[r_real > 0] # Ens quedem amb les solucions positives

  # Vector que contindrà les solucions:
  solutions = np.empty((len(r_real_positive),6))

  # Iterem per cada solució real
  for i in range(len(r_real_positive)):
    # r(i)
    r = r_real_positive[i]
    # rho = (r**3-1)/(C*r**3)
    rho = K/keta2*(r**3-1)/r**3 *np.dot(r_earth,nhat)
    # rho_t:
    rho_t = 1/(2*eta)*(K*(r**3-1)/r**3*np.dot(r_earth,vhat) - rho*eta_t)
    # rhovec:
    rhovec = rho*rhohat
    # rhovec_t
    rhovec_t = rho_t*rhohat + rho*eta*vhat
    # posicio-velocitat asteroide
    x = np.concatenate((r_earth+rhovec,v_earth+rhovec_t))
    # Guardem les solucions a la matriu.
    solutions[i] = x

  return solutions

rade = x.flatten(order='F')

r_earth = np.array([np.cos(tiempo_medio), np.sin(tiempo_medio), 0])

v_earth = np.array([-np.sin(tiempo_medio), np.cos(tiempo_medio), 0])

sol = laplace(rade, r_earth, v_earth, K = 332946./332947.)
print(sol)

[[ 3.06773745e+00 -7.54030554e-02 -4.19126327e-01 -1.71480038e-02
   5.37883475e-01  8.55383193e-02]
 [ 9.99559424e-01 -2.96809475e-02 -3.17811096e-15  2.96809475e-02
   9.99559424e-01  6.48611773e-16]
 [-7.40380520e-01  8.78465880e-03  3.52607284e-01  6.90777315e-02
   1.38796333e+00 -7.19626340e-02]]


### `car2kep`

In [12]:
import numpy as np

def car2kep(x, K = 332946./332947.):
  """
  car2kep(x, K = 332946./332947.) transforma les coordenades cartesianes d'una
     òrbita el·líptica als seus elements orbitals keplerians.

  INPUT:
    - x: array unidimensional que conté la posició (x,y,z) i velocitat (v_x,v_y,v_z)
         de l'objecte.
    - K: paràmetre opcional que conté el quadrat de la constant de Gauss en les
         unitats adients.
  OUTPUT:
    - array unidimensional que conté, per ordre, els valors de:
        - a (semieix major [AU])
        - e (excentricitat)
        - i (inclinació [graus])
        - Omega (longitud del node ascendent [graus])
        - omega (argument del periàpside [graus])
        - M (anomalia mitjana [graus])
  """

  # Posició, velocitat i moment angular:
  r = x[0:3]
  v = x[3:6]
  c = np.cross(r,v)

  # Norma euclidiana de la posició, la velocitat i el moment angular.:
  rnorm = np.linalg.norm(r)
  vnorm = np.linalg.norm(v)
  cnorm = np.linalg.norm(c)

  # Vector excentricitat i excentricitat
  ecc = ((vnorm*vnorm-K/rnorm)*r - np.dot(r,v)*v)/K;
  e = np.linalg.norm(ecc)

  # Vector n i la seva norma:
  n = np.array([-c[1], c[0], 0])
  nnorm = np.linalg.norm(n)

  # Anomalia verditable:
  if e*rnorm != 0:
    ang = np.max([np.min([np.dot(ecc,r)/(e*rnorm),1]),-1]) # ang\in[-1,1]
  else:
    ang = 0 # Per e = 0 no està ben definit...
  nu = np.arccos(ang)
  if np.dot(r,v) < 0:
    nu = 2*np.pi-nu

  # Inclinació:
  i = np.arccos(c[2]/cnorm)

  # Anomalia excèntrica:
  E = 2*np.arctan(np.tan(nu/2)/np.sqrt((1+e)/(1-e)))

  # Anomalia mitjana:
  M = E-e*np.sin(E)

  # Longitud del node ascendent:
  if nnorm != 0:
    ang = np.max([np.min([n[0]/nnorm,1]),-1]) # ang\in[-1,1]
  else:
    ang = 0
  Omega = np.arccos(ang)
  if n[1] < 0:
    Omega = 2*np.pi - Omega

  # Argument del periàpside:
  if nnorm*e != 0:
    ang = np.max([np.min([np.dot(n,ecc)/(nnorm*e),1]),-1]) # ang\in[-1,1]
  else:
    ang = 0
  omega = np.arccos(ang)
  if ecc[2] < 0:
    omega = 2*np.pi - omega

  # Semi-eix major:
  a = 1/(2/rnorm - vnorm*vnorm/K)

  return np.array([a,                 # semi-eix major (AU)
                   e,                 # excentricitat
                   np.rad2deg(i),     # inclinació (graus)
                   np.rad2deg(Omega), # longitud del node ascendent (graus)
                   np.rad2deg(omega), # argument del periàpside (graus)
                   np.rad2deg(M)      # anomalia mitjana (graus)
                  ])

x1 = sol[0, :]
x2 = sol[1, :]
x3 = sol[2, :]

elem_orb1 = car2kep(x1, K = 332946./332947.)
elem_orb2 = car2kep(x2, K = 332946./332947.)
elem_orb3 = car2kep(x3, K = 332946./332947.)

### Lectura de les dades dels 2024 primers asteroides numerats

Per llegir el fitxer `numbered_asteroids_2024.csv` i manipular-lo, pot ser d'ajuda utilitzar el següent codi:

In [17]:
import numpy as np
import pandas as pd

def norma_euclidiana(v):
    return np.sqrt(np.sum(v**2))

def norma_1(vector):
    """Calcula la norma 1 de un vector."""
    return np.sum(np.abs(vector))

def norma_inf(vector):
    """Calcula la norma infinito de un vector."""
    return np.max(np.abs(vector))

# Llegim el fitxer:
df = pd.read_csv("numbered_asteroids_2024.csv")

num_values = df.iloc[:, 2:7].to_numpy(dtype = np.float64)

# Vectores elem_orb1, elem_orb2 y elem_orb3
vectores_elem = [elem_orb1[:-1], elem_orb2[:-1], elem_orb3[:-1]]   #le quitamos el último elemento a cada array de elementos orbitales

# Inicializamos las normas mínimas con un valor grande
norma_minima_euclidiana = np.inf
norma_minima_1 = np.inf
norma_minima_inf = np.inf
indice_fila_min_norma_euclidiana = 0
indice_fila_min_norma_1 = 0
indice_fila_min_norma_inf = 0

# Iteramos sobre todas las filas de num_values
for i, fila in enumerate(num_values):
    # Calculamos las normas de la diferencia entre la fila y cada vector elem_orbi
    norma_euclidiana_diff = [norma_euclidiana(fila - vector_elem) for vector_elem in vectores_elem]
    norma_1_diff = [norma_1(fila - vector_elem) for vector_elem in vectores_elem]
    norma_inf_diff = [norma_inf(fila - vector_elem) for vector_elem in vectores_elem]

    # Encontramos las normas mínimas
    min_norma_euclidiana_actual = min(norma_euclidiana_diff)
    min_norma_1_actual = min(norma_1_diff)
    min_norma_inf_actual = min(norma_inf_diff)

    # Si la norma mínima actual es menor que la mínima anterior, actualizamos
    if min_norma_euclidiana_actual < norma_minima_euclidiana:
        norma_minima_euclidiana = min_norma_euclidiana_actual
        indice_fila_min_norma_euclidiana = i
    if min_norma_1_actual < norma_minima_1:
        norma_minima_1 = min_norma_1_actual
        indice_fila_min_norma_1 = i
    if min_norma_inf_actual < norma_minima_inf:
        norma_minima_inf = min_norma_inf_actual
        indice_fila_min_norma_inf = i

# Imprimimos los números de las filas con las normas mínimas
print("El número de la fila con la norma Euclidiana mínima es:", indice_fila_min_norma_euclidiana)
print("El número de la fila con la norma 1 mínima es:", indice_fila_min_norma_1)
print("El número de la fila con la norma infinito mínima es:", indice_fila_min_norma_inf)


El número de la fila con la norma Euclidiana mínima es: 697
El número de la fila con la norma 1 mínima es: 697
El número de la fila con la norma infinito mínima es: 697


Vemos que el asteroide que buscamos es el 698, a cuya información podemos acceder:

In [14]:
print(df.iloc[697])

full_name       698 Ernestina (A910 ED)
pdes                                698
a                              2.866292
e                              0.111205
i                             11.532454
om                            40.614687
w                             98.132492
ma                           154.038412
epoch_mjd                         60200
Name: 697, dtype: object
